eureka:
  client:
    service-url:
      defaultZone: http://eureka-first:9001/eureka/
---
server:
  port: 8001
spring:
  profiles: first
  application:
    name: api-service-a
---
server:
  port: 8002
spring:
  profiles: second
  application:
      name: api-service-b
---
