server:
  port: 8008
spring:
  application:
    name: api-service
  cloud:
    #使用consul，注册为服务，同时也可以通过consul获取其他服务并调用
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        # 如果不设置为true/service-name，需要在调用端hosts里配置服务名和ip映射
        prefer-ip-address: false
        # 注册到consul的serviceId，会注册dns解析
        service-name: ${spring.application.name}
      enabled: true
management:
  security:
    enabled: false
