spring:
  application:
    #eureka 服务名
    name: registry-center
server:
  port: ${port:9001}
eureka:
  server:
    #单机情况下启用会导致页面红色提示
    enable-self-preservation: false
  instance:
    hostname: eureka-first
  #client单机设置
  client:
    #不注册称为服务
    register-with-eureka: false
    #不检索服务
    fetch-registry: false
    #map键值对，服务注册和发现地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
