server:
  port: 11111
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka-first:9001/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: api-service-a
    api-b:
      path: /api-b/**
      serviceId: api-service-b