server:
  port: 8009
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      discovery:
        enabled: true
        prefer-ip-address: false
management:
  security:
    enabled: false